version: '3.7'

services:
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'your_db_name'
      MYSQL_USER: 'your_username'
      MYSQL_PASSWORD: 'your_password'
      MYSQL_ROOT_PASSWORD: 'your_password'

  web:
    build:
      context: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db