version: "3"

services:
  db:
    image: postgres:13
    env_file: .env

  web:
    build:
      context: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


# Due to problems with my computer, I cannot use MYSQL but leave the file ready to run on another computer

# version: '3'
# services:
#   db:
#     image: mysql:8
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_DATABASE='mydatabase'
#       - MYSQL_USER='root'
#       - MYSQL_PASSWORD='some_password'
#       - MYSQL_ROOT_PASSWORD='some_password'
#       - MYSQL_HOST=''
#     volumes:
#       - /tmp/app/mysqld:/var/run/mysqld
#       - ./db:/var/lib/mysql
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - /tmp/app/mysqld:/run/mysqld
#     depends_on:
#       - db